### ISSUE TITLE
How does one set this up?

### ISSUE THREAD

**Issue by WithinAmnesia** [don-tnowe/godot-wyvernshield-triggers#1]
![image](https://github.com/don-tnowe/godot-wyvernshield-triggers/assets/86871191/da04878b-d5d5-47ce-89e3-a90955acb0e0)
I have a new project I copy pasted the zip contents into the directory and I get this error trying to run this. I am not sure what should be done next. It looks like quite a lot of work went into this and it looks quite detailed but I'm not sure how to set this up to test it out? I read the set up but its not clicking what to do in my mind at least. What is needed to see how this works from a fresh project? @don-tnowe 

https://github.com/don-tnowe/godot-wyvernbox-inventory/issues/3#issuecomment-1646805764
"But you can see how combat can be done in Wyvernshield's Example project (basically just clone https://github.com/don-tnowe/godot-wyvernshield-triggers) and adapt to how you see fit." I am trying to do this yet I lack the current understanding how to operate this quite right to set it up correctly?

https://github.com/don-tnowe/godot-wyvernshield-triggers#setup
   "Give your actors a TriggerReactionContainer and/or a StatSheet
    The Resources inside these two objects can be defined locally or saved as files.
    To edit trigger parameters and their result object's properties, click the View Database button inside a TriggerReaction."
I am not sure what this means to do in Godot to fulfill these requirements? Is there a CC0 general use demo or something that can be unzipped and played without specific tinkering around like I am not sure what to do? I am not super accurately able to easily figure this out for I'm lacking the knowledge to set this up correctly currently. What is needed?

**Comment by don-tnowe** [comment]
See [godot-wyvernbox-inventory/#2](https://github.com/don-tnowe/godot-wyvernbox-inventory/issues/2).

Once you install the plugin correctly, on the menu bar in the top-left you do `Project -> Project Settings -> Plugins` and enable it.

Also, you don't need to `@ping` me, this is my repo, I'll get a notification anyway 😉

**Comment by WithinAmnesia** [comment]
![image](https://github.com/don-tnowe/godot-wyvernshield-triggers/assets/86871191/de0601ae-cc7f-45c0-92f5-9783eb2a72c3)
I got it to load up!
 
 https://github.com/don-tnowe/godot-wyvernbox-inventory/issues/2#issuecomment-1614411406
"I can't really fix this. This issue happens because paths in scene files are absolute (e.g. "res://example/graphics/font.ttf" not "<current folder>/graphics/font.ttf") I see in your FS dock the example and addons folders are in a sub-folder godot-wyvernbox-inventory, not in the root directory - try:"
 
Simple solution: (e.g. "res://example/graphics/font.ttf") <- do this. 
![image](https://github.com/don-tnowe/godot-wyvernshield-triggers/assets/86871191/5f6baf23-b3c9-4a69-bcb8-f79252b8cabc)
For simple solution make sure the these files are beside each other:
- project.godot
- example
- addons

Then it should load up in Godot 4+!
